name: ansible test integration
description: configure cloud environment and run ansible-test integration tests
inputs:
  collection_path:
    description: Relative path where to run `ansible-test integration` command.
    required: true
  python_version:
    description: Python version to use to run integration tests
    required: true
  ansible_version:
    description: ansible-core version to use to run integration tests
    required: true
  ansible_test_targets:
    description: Integration tests targets
    required: false
  ansible_test_environment:
    description: list of environment variables to set when running ansible-test
    required: false

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python_version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install wheel now for faster builds
      run: python3 -m pip install wheel --upgrade
      shell: bash

    - name: Install ansible-core (${{ inputs.ansible_version }})
      run: python3 -m pip install https://github.com/ansible/ansible/archive/${{ inputs.ansible_version }}.tar.gz --disable-pip-version-check
      shell: bash

    - name: Disable selinux with selinux_please_lie_to_me
      run: |
        python3 -m pip uninstall -y selinux
        python3 -m pip install selinux_please_lie_to_me
      shell: bash

    - name: Install collection python requirements
      run: python3 -m pip install -r requirements.txt -r test-requirements.txt
      shell: bash
      working-directory: ${{ inputs.collection_path }}

    - name: Set environment variables
      run: echo "${{ inputs.ansible_test_environment }}" >> $GITHUB_ENV
      shell: bash
      if: inputs.ansible_test_environment != ''

    - name: Run integration tests
      run: >-
        ansible-test integration
        --diff
        --no-temp-workdir
        --color
        --skip-tags False
        --retry-on-error
        --continue-on-error
        --python ${{ inputs.python_version }}
        -v
        ${{ inputs.ansible_test_targets }}
      shell: bash
      working-directory: ${{ inputs.collection_path }}
